words = [
    "caddy",
    "chmod",
    "chown",
    "disko",
    "gnugrep",
    "gnused",
    "mkdir",
    "nixos",
    "nixpkgs",
    "pkgs",
    "rafaelcga",
    "tty",
]
ignore_paths = [".git/**/*"]
