name: Test NixOS Configuration

on:
  push:
    paths-ignore:
      - ".github/**"
  pull_request:
    paths-ignore:
      - ".github/**"
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  discover-hosts:
    name: Discover NixOS hosts
    runs-on: ubuntu-latest
    outputs:
      hosts: ${{ steps.get-hosts.outputs.hosts }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Get NixOS hosts from directories
        id: get-hosts
        run: |
          JSON_LIST=$(find ./hosts -mindepth 1 -maxdepth 1 -type d | xargs -n 1 basename | jq -R . | jq -sc .)
          echo "hosts=$JSON_LIST" >> "$GITHUB_OUTPUT"

  build-hosts:
    name: Build ${{ matrix.host }}
    runs-on: ubuntu-latest
    needs: discover-hosts
    strategy:
      fail-fast: false
      matrix:
        host: ${{ fromJSON(needs.discover-hosts.outputs.hosts) }}
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v15
        with:
          name: rafaelcga
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build and test flake
        run: |
          nix flake check
          nix build -L .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
